In [31]:
import tensorflow as tf;

In [32]:
rand = tf.random.uniform([1], 0, 1)    
#random.uniform( [배열형태], 랜덤값의 최솟값, 랜덤값의 최댓값 )  <-- 인자로 dtype, name 등 추가 가능

In [33]:
rand

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.17573607], dtype=float32)>

In [34]:
rand2 = tf.random.uniform([2, 2], 0, 1, dtype=tf.dtypes.float64)
rand2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.31575614, 0.59793036],
       [0.52561252, 0.81956675]])>

In [35]:
rand2.shape
rand2.dtype

tf.float64

In [36]:
rand3= tf.random.uniform([4], 0, 1)
rand3

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.57506084, 0.6297666 , 0.7244046 , 0.7621589 ], dtype=float32)>

# **뉴런만들기**

In [37]:
#[1] 활성화함수 만들기: sigmoid
#활성화함수: sigmoid, reLU

import math

def sigmoid(x):
    return 1 / (1 + math.exp(-x))

#[2] 뉴런의 입력과 출력 정의하기
#입력이 1일 때 기대출력이 0이 되는 뉴런: 
x = 1
y = 0

w = tf.random.normal([1], 0, 1)      #<------ 뉴런! 
#random.normal(): 정규분포로부터 난수값 반환 
#random.normal( [반환값 텐서의 형태], 정규분포의 평균(0), 정규분포의 표준편차(1) )
output = sigmoid(x * w)

print(output)

#error 구하기
y_error = y - output

#[3]내가 원하는 값(y)이 나오도록 뉴런(가중치) 조절하기: 경사하강법(Gradient Descent)
#경사하강법: 가중치(w)에 (입력 * 학습률 * 에러)를 더해주는 것 
#  --손실곡선의 기울기. 손실곡선을 미분한 다음 그 값을 이용해서 가중치가 손실이 가장 낮아지는 지점에 도달하도록 반복 계산
for i in range(1000):
    output = sigmoid(x * w)
    error = y - output
    w = w + x * 0.1 * error     #학습률: 0.1
    
    if i % 100 == 99:
        print(i, error, output)

0.2725548088590048
99 -0.08199760656834773 0.08199760656834773
199 -0.04626696103821343 0.04626696103821343
299 -0.03200138464986776 0.03200138464986776
399 -0.02440024700051744 0.02440024700051744
499 -0.01969476285274087 0.01969476285274087
599 -0.01650065237874846 0.01650065237874846
699 -0.014192833499124995 0.014192833499124995
799 -0.012448387359154227 0.012448387359154227
899 -0.011084002812361148 0.011084002812361148
999 -0.00998801554741427 0.00998801554741427


In [38]:
#입력이 0일 때 기대출력이 1이 되는 뉴런:
x = 0
y = 1
w = tf.random.normal([1], 0, 1)

for i in range(1000):
    output = sigmoid(x * w)
    error = y - output
    w = w + x * 0.1 * error
    
    if i % 100 == 99:
        print(i, error, output)
        
#[!] 결과값이 같다: 0을 곱하기 때문에 w가 변하지 않는다. 
# =한 값만 나온다.
# =편향된 값만 나온다. 
#-----> 편향된 값만 나오는 것을 방지하기 위해 '편향(bias)'를 뉴런에 적용시킨다. 

99 0.5 0.5
199 0.5 0.5
299 0.5 0.5
399 0.5 0.5
499 0.5 0.5
599 0.5 0.5
699 0.5 0.5
799 0.5 0.5
899 0.5 0.5
999 0.5 0.5


In [39]:
#입력이 0일 때 기대출력이 1이 되는 뉴런의 학습에 편향 더하기:
x = 0
y = 1
w = tf.random.normal([1], 0, 1)
b = tf.random.normal([1], 0, 1)    #편향으로는 보편적으로 1을 사용한다. 

for i in range(1000):
    output = sigmoid(x * w + 1 * b)
    error = y - output
    w = w + x * 0.1 * error
    b = b + 1 * 0.1 * error
    
    if i % 100 == 99:
        print(i, error, output)

99 0.07094603777373032 0.9290539622262697
199 0.04241546691684117 0.9575845330831588
299 0.03008673251101679 0.9699132674889832
399 0.023263438441313067 0.9767365615586869
499 0.018944290987143675 0.9810557090128563
599 0.015969077105946083 0.9840309228940539
699 0.013796927970618045 0.986203072029382
799 0.012142290319060445 0.9878577096809396
899 0.010840382165573259 0.9891596178344267
999 0.0097895598467298 0.9902104401532702


# **첫 번째 신경망 네트워크: AND**

In [40]:
#두 개의 입력을 받는 AND 연산 
#입력값 두개가 모두 참일때만 참 반환

#cf. True, False로 어떤 수를 사용해야할까? (딥러닝의 주요 입력값은 int 또는 float!)
print('True는', int(True),
     'False는', int(False),
     '을 사용하자')

import numpy as np

x = np.array([[1, 1], [1, 0], [0, 1], [0, 0]])
y = np.array([[1], [0], [0], [0]])

w = tf.random.normal([2], 0, 1)
b = tf.random.normal([1], 0, 1)
b_x = 1

for i in range(2000):
    error_sum = 0
    for j in range(4):
        output = sigmoid(np.sum(x[j] * w) + b_x * b)
        error = y[j][0] - output
        w = w + x[j] * 0.1 * error
        b = b + b_x * 0.1 * error
        error_sum += error
        
    if i % 200 == 199:
        print(i, error_sum)
        
#AND 네트워크 평가하기
for i in range(4): 
    print('X:', x[i], 'Y:', y[i], 'Output:', sigmoid(np.sum(x[i]*w)+b))

True는 1 False는 0 을 사용하자
199 -0.10559216756567036
399 -0.06401694892877259
599 -0.04580654745801787
799 -0.035561061855791457
999 -0.029009439070860392
1199 -0.02446909690814023
1399 -0.02114209357755427
1599 -0.018601673845089244
1799 -0.01660027969979116
1999 -0.014983499541940061
X: [1 1] Y: [1] Output: 0.9650203207486281
X: [1 0] Y: [0] Output: 0.024789051977628287
X: [0 1] Y: [0] Output: 0.024864379094507314
X: [0 0] Y: [0] Output: 2.3493239256199956e-05


# **두 번째 신경망 네트워크: OR**

In [41]:
x = np.array([[1, 1], [1, 0], [0, 1], [0, 0]])
y = np.array([[1], [1], [1], [0]])

w = tf.random.normal([2], 0, 1)
b = tf.random.normal([1], 0, 1)
b_x = 1

for i in range(2000):
    error_sum = 0
    for j in range(4):
        output = sigmoid(np.sum(x[j] * w) + b_x * b)
        error = y[j][0] - output
        w = w + x[j] * 0.1 * error
        b = b + b_x * 0.1 * error
        error_sum += error
        
    if i % 200 == 199:
        print(i, error_sum)
        
#OR 네트워크 평가하기
for i in range(4): 
    print('X:', x[i], 'Y:', y[i], 'Output:', sigmoid(np.sum(x[i]*w)+b))

199 -0.048283128196595304
399 -0.025528192246457304
599 -0.01723723739441667
799 -0.01296647707506321
999 -0.010372994898457708
1199 -0.008635228027301337
1399 -0.007391663459512796
1599 -0.0064579576258035065
1799 -0.005732655204398401
1999 -0.005151416835960616
X: [1 1] Y: [1] Output: 0.9999972026832725
X: [1 0] Y: [1] Output: 0.9897886904430638
X: [0 1] Y: [1] Output: 0.9897608545963603
X: [0 0] Y: [0] Output: 0.02554077874642858


# **세 번째 신경망 네트워크: XOR**

In [42]:
#XOR: 홀수개의 입력이 참일때만 결괏값이 참이된다
#입력값이 2개일 떄: 2개의 입력값이 다를 때 참이된다. 

x = np.array([[1, 1], [1, 0], [0, 1], [0, 0]])
y = np.array([[0], [1], [1], [0]])

w = tf.random.normal([2], 0, 1)
b = tf.random.normal([1], 0, 1)
b_x = 1

for i in range(2000):
    error_sum = 0
    for j in range(4):
        output = sigmoid(np.sum(x[j] * w) + b_x * b)
        error = y[j][0] - output
        w = w + x[j] * 0.1 * error
        b = b + b_x * 0.1 * error
        error_sum += error
        
    if i % 200 == 199:
        print(i, error_sum)
        
#XOR 네트워크 평가하기
for i in range(4): 
    print('X:', x[i], 'Y:', y[i], 'Output:', sigmoid(np.sum(x[i]*w)+b))
    
#[!]에러값이 변하다가 '어느 시점'부터 변하지 않는다: 
#output을 구성하는 w와 b 출력해보기: 
print('w:', w)    #----> 첫번째 입력이 두번째 입력보다 큰 영향
print('b:', b)    #----> 두번째 입력과 비슷하게 거의 영향이 없다
#네트워크가 어떤 일을 하려는지 불명확함. ==>여러 개의 퍼셉트론을 사용하자!

199 -0.0007656919533299833
399 -3.11181452899989e-05
599 -1.2685581677329694e-06
799 -1.3960657518907738e-08
999 3.722842145670313e-09
1199 3.722842145670313e-09
1399 3.722842145670313e-09
1599 3.722842145670313e-09
1799 3.722842145670313e-09
1999 3.722842145670313e-09
X: [1 1] Y: [0] Output: 0.5128176286712095
X: [1 0] Y: [1] Output: 0.5128176305326305
X: [0 1] Y: [1] Output: 0.4999999990686774
X: [0 0] Y: [0] Output: 0.5000000009313226
w: tf.Tensor([ 5.1281754e-02 -7.4505806e-09], shape=(2,), dtype=float32)
b: tf.Tensor([3.7252903e-09], shape=(1,), dtype=float32)


In [43]:
#tf.keras를 이용한 XOR 네트워크 계산하기

x = np.array([[1, 1], [1, 0], [0, 1], [0, 0]])
y = np.array([[0], [1], [1], [0]])

model = tf.keras.Sequential([
    tf.keras.layers.Dense(units = 2, activation = 'sigmoid', input_shape = (2, )),
    tf.keras.layers.Dense(units = 1, activation = 'sigmoid')
])
#model: 딥러닝 계산을 위한 여러 함수와 변수의 묶음딥러닝을 계산하는 가장 핵심적인 단위

#tf.keras.Sequential: 
#model에서 가장 많이 쓰이는 구조. 
#순차적으로 뉴런과 뉴런이 합쳐진 단위(레이어)를 일직선으로 배치하는 것.
#=시퀀셜 네트웤, 시퀀셜 모델
#인수: 레이어가 차례대로 정의된 리스트 전달

#tf.keras.layers.Dense: 
#레이어 정의 명령어. Dense는 가장 기본적인 레이어. 
#레이어 입출력 사이에 있는 모든 뉴런이 서로 연결되는 레이어. 

#units: 레이어를 구성하는 뉴런 수. cf.뉴런이 많을수록 레이어 성능 좋아지지만 메모리 UP

#input_shape: 시퀀셜모델의 첫번쩨 레이어에서만 정의.입력의 차원 수가 어떻게 되는지 정의.

model.compile(optimizer = tf.keras.optimizers.SGD(lr = 0.1), loss = 'mse')
#optimizer: 최적화함수. 딥러닝의 학습식 정의.

#SGD: 경사하강법(Stochastic Gradient Descent)
#가중치(w)에 (입력 * 학습률 * 에러)를 더해주는 것 
#  --손실곡선의 기울기. 손실곡선을 미분한 다음 그 값을 이용해서 가중치가 손실이 가장 낮아지는 지점에 도달하도록 반복 계산
#  --가중치를 업데이트할 때 미분을 통해 기울기를 구한 다음 기울기가 낮은 쪽으로 업데이트하겠다! 
#'stochastic': 전체를 한번에 계산하지 않고 확률적으로 일부 샘플을 구해서 조금씩 나눠 계산하겠다!
#cf. 구글 머신러닝 단기집중과정의 "손실줄이기"참고  --bit.ly/2PlcKkC

#loss: error와 비슷한 개념. 손실을 줄이는 방향으로 학습. 

#mse: 평균제곱오차(Mean Squared Error)
#기대출력에서 실제 출력을 뺀 뒤 제곱한 값을 평균

model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 2)                 6         
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 3         
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [46]:
#tf.keras를 이용한 2-레이어 XOR 네트워크 학습:
history = model.fit(x, y, epochs=2000, batch_size = 1)
#epochs: 훈련 데이터를 반복 학습시키는 횟수.
#batch_size: 한번에 학습시키는 데이터 수. 각 에포크에 학습시키는 훈련 데이터의 수.
# --1로 지정 ==> 입력을 넣었을 때 정확한 값을 출력하는지 알아보기 위해
#첫번째, 두번째 인자로서의 x, y: 입력, 기대출력

#상기 학습모델 평가하기: 
model.predict(x)
# ==> 레이어를 추가하기 전보다 학습을 잘 하고 있다.
#     이유: model을 구성하고 있는 파라미터(가중치, 편향) 확인해보기: 
for weight in model.weights: 
    print(weight)
#model.weights: 가중치정보가 저장되어 있는 곳. 
#kernel: 입력-레이어, 레이어-레이어 사이의 뉴런을 연결할 때 사용되는 가중치
#bias: 편향과 연결된 가중치
#가중치들을 그래프로 나타내보면 레이어 추가 전보다 가중치들이 무슨 일을 하는지 가시적이지 않음. 
# --> 가중치시각화보다 네트워크의 학습상황을 더 잘 파악할 수있는 방법 필요

<tf.Variable 'dense_4/kernel:0' shape=(2, 2) dtype=float32, numpy=
array([[-4.803235 ,  1.7984445],
       [-4.8915677,  1.8664836]], dtype=float32)>
<tf.Variable 'dense_4/bias:0' shape=(2,) dtype=float32, numpy=array([ 0.9655306, -2.5677779], dtype=float32)>
<tf.Variable 'dense_5/kernel:0' shape=(2, 1) dtype=float32, numpy=
array([[-4.990222 ],
       [-3.4744844]], dtype=float32)>
<tf.Variable 'dense_5/bias:0' shape=(1,) dtype=float32, numpy=array([2.1152356], dtype=float32)>
